version: 2

jobs:

  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "HELLO WORLD" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
      
  test-a:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
        # absolute or relative path from working_directory
          at: my_workspace
      - run: |
          # this will fail intentionally, we'll use SSH to debug and fix
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi   

  test-b:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
        # absolute or relative path from working_directory
          at: my_workspace
      - run: cat my_workspace/echo-output
      
  test-c:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A fourth hola"

  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
        # absolute or relative path from working_directory
          at: my_workspace
      - run: |
          echo "Deploying!"
          cat my_workspace/echo-output
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-a:
          # only run if build succeeds
          requires:
            - build
      - test-b:
          # only run if build succeeds
          requires:
            - build
      - test-c:
          # integration test
          # only run if build succeeds
          requires:
            - test-a
            - test-b
      - deploy:
          # only run if build succeeds
          requires:
            - test-c
