version: 2

jobs:

  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      
  test-a:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hi"
      - run: sleep 5

  test-b:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A third salut"
      - run: sleep 5
      
  test-c:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A fourth hola"
      - run: sleep 5

  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A final farewell"
      - run: sleep 5
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-a:
          # only run if build succeeds
          requires:
            - build
      - test-b:
          # only run if build succeeds
          requires:
            - build
      - test-c:
          # integration test
          # only run if build succeeds
          requires:
            - test-a
            - test-b
      - deploy:
          # only run if build succeeds
          requires:
            - test-c
