version: 2.1

jobs:
  build:
    docker: #macos, gpu, machine
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  test:
    docker: #macos, gpu, machine
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hi"
      - run: sleep 5

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
